### ISSUE TITLE
可不可以支持下后台下载呢 

### ISSUE THREAD

**Issue by ghost** [install-b/OfflineBreakpointDownload#1]
关闭屏幕后会网络中断 希望能够继续保持下载

**Comment by install-b** [comment]
这个句柄方式追加方式不支持后台下载，创建通过创建 'NSURLSessionDownloadTask' 参考：http://www.jianshu.com/p/1211cf99dfc3   ，如果你有更好的方式，可以分享出来学习。
  感谢你的意见，以后会继续优化的。
