### ISSUE TITLE
音频下载内存过高  闪退 求助

### ISSUE THREAD

**Issue by yangfangxue** [install-b/OfflineBreakpointDownload#2]
音频下载内存过高  闪退 求助

**Comment by install-b** [comment]
你的音频文件是多大的。 方不方便提供资源文件的URL

**Comment by yangfangxue** [comment]
http://120.25.235.75/cgi-bin/MusicFiles/Beyond-NoMore.mp3
 http://120.25.235.75/cgi-bin/MusicFiles/Faded-Broken1.mp3
 http://120.25.235.75/cgi-bin/MusicFiles/Faded-Broken2.mp3
 http://120.25.235.75/cgi-bin/MusicFiles/Faded-Full.mp3
  http://120.25.235.75/cgi-bin/MusicFiles/Korea-Sliding.mp3
  http://120.25.235.75/cgi-bin/MusicFiles/Lilonghao-OldStreet.mp3
  http://120.25.235.75/cgi-bin/MusicFiles/NT-RockHead.mp3
  http://120.25.235.75/cgi-bin/MusicFiles/TezCadey1.mp3
   http://120.25.235.75/cgi-bin/MusicFiles/TezCadey2.mp3
  http://120.25.235.75/cgi-bin/MusicFiles/XuweiTimes.mp3

**Comment by yangfangxue** [comment]
以上为mp3文件、都不是太大   我项目的界面是点击一个音乐下载一个显示进度   我下载第一个没问题  但当我下完第一个 再下第二个的时候或者第三个的时候 内存就猛的往上升 控制台提示内存溢出 然后就崩了

**Comment by yangfangxue** [comment]
不知道楼主有没有关于这个mp3文件的处理  我想把这些mp3文件下载到本地沙盒 然后拿到这些文件的path做一个音频和视频合成的一个功能  音视频合成功能我已经实现 现在遇到的就是使用你的这个库遇到下载内存溢出闪退的问题

**Comment by yangfangxue** [comment]
楼主如有时间 请帮我看看是什么问题 我也会再找找 试试其他的库看看是不是同样的问题

**Comment by yangfangxue** [comment]
Message from debugger: Terminated due to memory issue

**Comment by install-b** [comment]
好的，我也测试一下，非常感谢你的反馈。

**Comment by install-b** [comment]
你好！ 我这边全部同时下载，我还同时下载了几个20多兆的文件 我看了Xcode 内存监控一直都是保持基本不变。 您说的内存飙升是不是下载完成后你全部加载到内存中了，你可以先试试只下载不做其他操作，先看看有没有变化。 如果只是下载就内存飙升了，可能是我这边逻辑出现bug了。

**Comment by yangfangxue** [comment]
好的 我再试试 只下载不做其他处理再试试   感谢指导

**Comment by yangfangxue** [comment]
找到原因了 果然 多谢楼主 是我的失误  不好意思 单独批量下载完全没有任何问题 是我这边的操作问题  若有打觉请多担待 轮子很nice  有空会阅读源码学习的  感谢 已Follow And Star

**Comment by install-b** [comment]
客气！我也要谢谢您的反馈，有了你们的反馈才会越做越好。
