### ISSUE TITLE
你好 求助 帮个忙 看一下 谢谢!

### ISSUE THREAD

**Issue by shenguanjiejie** [install-b/OfflineBreakpointDownload#3]
![image](https://user-images.githubusercontent.com/9425605/34149147-1b6eacc6-e4df-11e7-8179-1e69b2e8a4a6.png)
![image](https://user-images.githubusercontent.com/9425605/34149165-2490a912-e4df-11e7-9255-cbab750e8928.png)
我执行 podilib lint ESPictureBrowser-SDWebImage.podspec --allow-warnings
虽然有warning 但是是成功的啊
![image](https://user-images.githubusercontent.com/9425605/34149333-b5e01998-e4df-11e7-8e6b-82074959b8dd.png)
没有相关经验,希望帮下忙 谢谢!

**Comment by shenguanjiejie** [comment]
因为看到你刚刚提交代码 感觉你应该还在 所以来问你一下😂 打扰了的话见谅 ...

**Comment by shenguanjiejie** [comment]
已经搞定了 ~ 打扰了

**Comment by install-b** [comment]
你好 感谢你的提问。
这个问题我之前有遇到过，虽然你已经解决了，我这里有一个方法可以解决那个问题不知道是不是跟你的一样。

新上架的pod 代码  不能search到解决方案

1. 删除本地pod索引 ：
 打开终端输入：$:rm ~/Library/Caches/CocoaPods/search_index.json  然后回车运行

2. 更新pod仓库  : 
终端输入：$: pod setup   然后回车运行 (这个过程会比较慢)

3. 然后再 pod search 你的库   搞定。

**Comment by shenguanjiejie** [comment]
哇 太热心了 谢谢了.我那天傻了 没有执行pod trunk push 给你点个start 以示感谢😄
